# -*- coding: utf-8 -*-
"""Network_Creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hd8SqLwjt5sZNnrFUPPtxFze0ui5G44W
"""

import networkx as nx
import matplotlib.pyplot as plt


G = nx.Graph()
G.add_node("A")
G.add_nodes_from(["B", "C", "D", "E"])
G.add_edge(*("A", "B"))
G.add_edges_from([("A", "C"), ("B", "D"), ("B", "E"), ("C", "E")])
print("Vertex set: ", G.nodes())
print("Edge set: ", G.edges())

nx.draw(G, with_labels=True)
plt.show()

nx.draw(G, with_labels=True, font_weight='bold')
plt.show()

GP = nx.petersen_graph()
nx.draw(GP, with_labels=True, font_weight='bold')
plt.show()

print(G.adj)

G.degree("A")

G = nx.Graph()
N = [('A', 'B', 2), ('A', 'C', 1), ('B', 'D', 5), ('B', 'E', 3), ('C', 'E', 2)]
G.add_weighted_edges_from(N)
print(nx.d_centrality(G))
nx.degree(G)

pos = nx.spring_layout(G)  # pos = nx.nx_agraph.graphviz_layout(G)
nx.draw_networkx(G, pos)
labels = nx.get_edge_attributes(G, 'weight')
nx.draw_networkx_edge_labels(G, pos, edge_labels=labels)
plt.show()
