# -*- coding: utf-8 -*-
"""readedgelist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zIzgldk8CPYLF-9v4DBZxb-8dtPp32ST
"""

import networkx as nx
import matplotlib.pyplot as plt

G = nx.path_graph(4)
# nx.draw(G)
nx.write_edgelist(G, "edgelist.txt")
fh = open("edgelist.txt", "r")
for line in fh.readlines():
    print(line)
list(G.edges)

# nx.draw(G)
# plt.show()
# fh.close()